In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(
    r"C:/Sachin/project/Bike-Taxi-Rides-Request-Demand-Forecast/data/raw_data.csv", 
    low_memory=False,
    compression="gzip"
)

In [3]:
len(df)

8381556

In [4]:
df.head()

                    ts number   pick_lat   pick_lng   drop_lat   drop_lng
0  2020-03-26 07:07:17  14626  12.313621  76.658195  12.287301  76.602280
1  2020-03-26 07:32:27  85490  12.943947  77.560745  12.954014  77.543770
2  2020-03-26 07:36:44  05408  12.899603  77.587300  12.934780  77.569950
3  2020-03-26 07:38:00  58940  12.918229  77.607544  12.968971  77.636375
4  2020-03-26 07:39:29  05408  12.899490  77.587270  12.934780  77.569950

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8381556 entries, 0 to 8381555
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   ts        str
 1   number    str
 2   pick_lat  float64
 3   pick_lng  float64
 4   drop_lat  float64
 5   drop_lng  float64
dtypes: float64(4), str(2)
memory usage: 383.7 MB

In [6]:
df.shape

(8381556, 6)

### A Customer_ID `number` at a particular timestamp can only have one entry
### Removing Duplicate Entries ['ts','number']

In [7]:
df[df.duplicated(subset=['ts','number'], keep=False)]

,ts,number,pick_lat,pick_lng,drop_lat,drop_lng
235,2020-03-26 18:10:35,16795,12.967236,77.641594,13.014504,77.650856
236,2020-03-26 18:10:35,16795,12.967236,77.641594,13.014504,77.650856
407,2020-03-26 21:35:50,65856,12.917173,77.586400,12.913940,77.685280
408,2020-03-26 21:35:50,65856,12.917173,77.586400,12.913940,77.685280
443,2020-03-26 23:26:29,27554,12.933715,77.619300,12.938208,77.587520
...,...,...,...,...,...,...
8381231,2021-03-26 22:23:12,61636,12.975229,77.620370,13.017285,77.618200
8381245,2021-03-26 22:25:13,61636,12.975229,77.620370,13.017285,77.618200
8381246,2021-03-26 22:25:13,61636,12.975229,77.620370,13.017285,77.618200
8381248,2021-03-26 22:25:27,61636,12.975229,77.620370,13.017285,77.618200
8381249,2021-03-26 22:25:27,61636,12.975229,77.620370,13.017285,77.618200

### There are 113540 Duplicate Entries
#### We have 8315498 Unique timestamp, customer_id rows.

In [8]:
## Keeping first occurence

df.drop_duplicates(subset=['ts','number'], keep ='first', inplace = True)

df.reset_index(drop = True, inplace = True)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8315498 entries, 0 to 8315497
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   ts        str
 1   number    str
 2   pick_lat  float64
 3   pick_lng  float64
 4   drop_lat  float64
 5   drop_lng  float64
dtypes: float64(4), str(2)
memory usage: 380.7 MB

In [10]:
df['number'] = pd.to_numeric(df['number'], errors='coerce')

#Count missing values
np.count_nonzero(df.isnull().values)

np.int64(116)

#### There are 116 NaN rows, dropping NaN rows.

In [11]:
df.dropna(inplace = True)
len(df)

8315382

In [12]:
df['number'] = pd.to_numeric(df['number'], errors='coerce', downcast='integer')
df['ts'] = pd.to_datetime(df['ts'], errors='coerce')

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 8315382 entries, 0 to 8315497
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   ts        datetime64[us]
 1   number    int32
 2   pick_lat  float64
 3   pick_lng  float64
 4   drop_lat  float64
 5   drop_lng  float64
dtypes: datetime64[us](1), float64(4), int32(1)
memory usage: 412.4 MB

### Breaking Time to Features

In [14]:
df['mins'] = df['ts'].dt.minute
df['hour'] = df['ts'].dt.hour
df['day'] = df['ts'].dt.day 
df['month'] = df['ts'].dt.month
df['year'] = df['ts'].dt.year   
df['dayofweek'] = df['ts'].dt.dayofweek

In [15]:
df

,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,mins,hour,day,month,year,dayofweek
0,2020-03-26 07:07:17,14626,12.313621,76.658195,12.287301,76.602280,7,7,26,3,2020,3
1,2020-03-26 07:32:27,85490,12.943947,77.560745,12.954014,77.543770,32,7,26,3,2020,3
2,2020-03-26 07:36:44,5408,12.899603,77.587300,12.934780,77.569950,36,7,26,3,2020,3
3,2020-03-26 07:38:00,58940,12.918229,77.607544,12.968971,77.636375,38,7,26,3,2020,3
4,2020-03-26 07:39:29,5408,12.899490,77.587270,12.934780,77.569950,39,7,26,3,2020,3
...,...,...,...,...,...,...,...,...,...,...,...,...
8315493,2021-03-26 23:55:24,50410,12.907856,77.557870,12.954270,77.530785,55,23,26,3,2021,4
8315494,2021-03-26 23:58:15,12580,12.981010,77.694450,12.969070,77.704280,58,23,26,3,2021,4
8315495,2021-03-26 22:11:20,72339,12.924252,77.650520,12.905820,77.630570,11,22,26,3,2021,4
8315496,2021-03-26 22:12:30,72339,12.924252,77.650520,12.905820,77.630570,12,22,26,3,2021,4
8315497,2021-03-26 15:00:55,28043,12.901222,77.594890,12.908599,77.649330,0,15,26,3,2021,4

In [16]:
df.to_csv('C:/Sachin/project/Bike-Taxi-Rides-Request-Demand-Forecast/data/preprocessed/preprocessed_1.csv',index = False, compression = 'gzip')

In [17]:
from geopy.distance import geodesic
from geopy.geocoders import Nominatim
import time
geolocator = Nominatim(user_agent="OLABikes")

## Data Cleaning with Business Understanding

### There can be cases when a user requests a ride, and their booking request is logged in our database but this user re-books his/her ride due to longer wait hours or driver refused booking or user by mistake added wrong pickup or drop locations. 

<hr>

### `Handle Case1 Rebooking Again to Same Location`: Keep only one request of same user to same pickup latitude longitude in 1hour time frame of first ride request.

<hr>

### `Handle Case2 Location entry mistake`: Keep only last request of user within 8mintues of first booking request.
#### A person booking a ride would generally book a ride that would take 8mins of bike ride time. 
#### Also, Calculate distance b/w pickup and drop. Based on distance and request time different remove bad data entries.

#### `Handle Case2.1`: Pick Up and Drop Lat-Long Distance less than 50meters = 0.05 kms; No user would like to ride for just 50meters trip. 

<hr>

### `Handle Case3`: Booking Location Outside operation zone of OLABikes

In [18]:
## Check lat-long bounding box coordinates

df['ts'] = pd.to_datetime(df['ts'])
df.sort_values(by = ['number','ts'], inplace = True)
df.reset_index(drop=True, inplace=True)

In [19]:
# you need convert first to numpy array by values and cast to int64 - output is in nanosecond, so need divide by 10 ** 9

df['booking_timestamp'] = df['ts'].astype('int64') // 10**9

In [20]:
df.head(20)

,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,mins,hour,day,month,year,dayofweek,booking_timestamp
0,2020-10-10 07:34:16,-1,12.975773,77.571070,12.878468,77.445330,34,7,10,10,2020,5,1602315
1,2020-10-11 08:23:42,-1,12.930813,77.609530,12.960320,77.587210,23,8,11,10,2020,6,1602404
2,2020-10-11 08:23:50,-1,12.930813,77.609530,12.960320,77.587210,23,8,11,10,2020,6,1602404
3,2020-10-11 08:23:51,-1,12.930813,77.609530,12.960320,77.587210,23,8,11,10,2020,6,1602404
4,2020-10-11 08:23:54,-1,12.930813,77.609530,12.960320,77.587210,23,8,11,10,2020,6,1602404
5,2020-10-11 08:23:56,-1,12.930813,77.609530,12.960320,77.587210,23,8,11,10,2020,6,1602404
6,2020-10-11 11:57:17,-1,12.960213,77.587460,12.930824,77.609610,57,11,11,10,2020,6,1602417
7,2020-10-11 11:57:31,-1,12.960213,77.587460,12.930824,77.609610,57,11,11,10,2020,6,1602417
8,2020-10-16 17:51:07,-1,12.924353,77.549410,12.932216,77.581825,51,17,16,10,2020,4,1602870
9,2020-10-16 17:51:25,-1,12.924353,77.549410,12.932216,77.581825,51,17,16,10,2020,4,1602870
10,2020-10-30 09:00:44,-1,12.945731,77.622500,12.973030,77.616840,0,9,30,10,2020,4,1604048
11,2020-11-27 20:16:20,-1,13.031985,77.571280,12.960211,77.646910,16,20,27,11,2020,4,1606508
12,2020-11-27 20:35:09,-1,13.031940,77.571260,12.960211,77.646910,35,20,27,11,2020,4,1606509
13,2020-11-27 20:35:48,-1,13.032073,77.571290,12.960211,77.646910,35,20,27,11,2020,4,1606509
14,2020-11-27 20:35:51,-1,13.032073,77.571290,12.960211,77.646910,35,20,27,11,2020,4,1606509
15,2020-12-05 22:09:55,-1,12.938531,77.578940,12.952660,77.568825,9,22,5,12,2020,5,1607206
16,2020-12-06 10:25:54,-1,12.933546,77.692894,12.977833,77.646830,25,10,6,12,2020,6,1607250
17,2020-12-06 10:34:20,-1,12.933337,77.691180,12.977833,77.646830,34,10,6,12,2020,6,1607250
18,2020-12-06 22:18:23,-1,12.938314,77.578830,12.952660,77.568825,18,22,6,12,2020,6,1607293
19,2020-12-06 22:19:39,-1,12.938314,77.578830,12.952660,77.568825,19,22,6,12,2020,6,1607293

In [21]:
df['shift_booking_ts'] = df.groupby('number')['booking_timestamp'].shift(1)
df['shift_booking_ts'] = df['shift_booking_ts'].fillna(0)

In [22]:
df['shift_booking_ts'] = df['shift_booking_ts'].astype('Int64')

In [23]:
df['booking_time_diff_hr'] = round((df['booking_timestamp'] - df['shift_booking_ts'])//3600)
df['booking_time_diff_min'] = round((df['booking_timestamp'] - df['shift_booking_ts'])//60)

In [24]:
##Booking time different in mins
df['booking_time_diff_min'].value_counts().to_dict()

{np.int64(0): 6138862,
 np.int64(1): 681469,
 np.int64(2): 290695,
 np.int64(4): 148657,
 np.int64(3): 130265,
 np.int64(5): 108979,
 np.int64(7): 66255,
 np.int64(8): 59919,
 np.int64(6): 52265,
 np.int64(10): 41527,
 np.int64(9): 34799,
 np.int64(11): 33833,
 np.int64(12): 24190,
 np.int64(14): 22861,
 np.int64(15): 20103,
 np.int64(13): 18722,
 np.int64(17): 17362,
 np.int64(18): 16798,
 np.int64(20): 14970,
 np.int64(21): 12639,
 np.int64(16): 12575,
 np.int64(19): 10571,
 np.int64(24): 10017,
 np.int64(23): 8740,
 np.int64(22): 8395,
 np.int64(25): 8352,
 np.int64(27): 8298,
 np.int64(30): 7707,
 np.int64(28): 7647,
 np.int64(31): 6458,
 np.int64(26): 6239,
 np.int64(34): 5413,
 np.int64(29): 5169,
 np.int64(33): 5055,
 np.int64(37): 4774,
 np.int64(40): 4703,
 np.int64(38): 4311,
 np.int64(32): 4202,
 np.int64(35): 4189,
 np.int64(41): 3976,
 np.int64(36): 3931,
 np.int64(44): 3457,
 np.int64(43): 3366,
 np.int64(39): 3143,
 np.int64(50): 3105,
 np.int64(47): 3066,
 np.int64(26420): 3063,
 np.int64(46): 2743,
 np.int64(48): 2628,
 np.int64(42): 2588,
 np.int64(51): 2557,
 np.int64(45): 2416,
 np.int64(54): 2399,
 np.int64(53): 2340,
 np.int64(26423): 2314,
 np.int64(60): 2213,
 np.int64(49): 2213,
 np.int64(57): 2190,
 np.int64(56): 1993,
 np.int64(63): 1753,
 np.int64(59): 1743,
 np.int64(61): 1740,
 np.int64(70): 1690,
 np.int64(52): 1671,
 np.int64(64): 1668,
 np.int64(67): 1650,
 np.int64(58): 1609,
 np.int64(55): 1596,
 np.int64(66): 1525,
 np.int64(69): 1376,
 np.int64(62): 1329,
 np.int64(73): 1294,
 np.int64(80): 1264,
 np.int64(74): 1246,
 np.int64(76): 1224,
 np.int64(65): 1212,
 np.int64(26426): 1175,
 np.int64(71): 1152,
 np.int64(77): 1147,
 np.int64(72): 1138,
 np.int64(68): 1126,
 np.int64(83): 1124,
 np.int64(79): 1050,
 np.int64(82): 1033,
 np.int64(86): 1002,
 np.int64(90): 1002,
 np.int64(75): 944,
 np.int64(87): 934,
 np.int64(84): 908,
 np.int64(89): 905,
 np.int64(26429): 895,
 np.int64(26424): 895,
 np.int64(78): 872,
 np.int64(93): 855,
 np.int64(92): 854,
 np.int64(96): 844,
 np.int64(100): 839,
 np.int64(26433): 838,
 np.int64(81): 819,
 np.int64(26425): 809,
 np.int64(103): 772,
 np.int64(85): 765,
 np.int64(26430): 750,
 np.int64(99): 747,
 np.int64(26427): 735,
 np.int64(97): 727,
 np.int64(95): 708,
 np.int64(26436): 687,
 np.int64(106): 682,
 np.int64(88): 676,
 np.int64(26422): 663,
 np.int64(26428): 659,
 np.int64(94): 658,
 np.int64(102): 657,
 np.int64(26421): 656,
 np.int64(109): 639,
 np.int64(112): 628,
 np.int64(105): 626,
 np.int64(26446): 612,
 np.int64(113): 610,
 np.int64(110): 599,
 np.int64(91): 594,
 np.int64(26449): 588,
 np.int64(119): 580,
 np.int64(98): 572,
 np.int64(115): 567,
 np.int64(26443): 566,
 np.int64(26439): 558,
 np.int64(107): 550,
 np.int64(122): 544,
 np.int64(101): 543,
 np.int64(116): 542,
 np.int64(108): 537,
 np.int64(123): 502,
 np.int64(104): 500,
 np.int64(26440): 494,
 np.int64(126): 485,
 np.int64(118): 484,
 np.int64(120): 472,
 np.int64(125): 471,
 np.int64(26437): 467,
 np.int64(129): 463,
 np.int64(111): 461,
 np.int64(132): 454,
 np.int64(26438): 454,
 np.int64(128): 447,
 np.int64(26459): 445,
 np.int64(26435): 441,
 np.int64(117): 433,
 np.int64(26456): 422,
 np.int64(136): 418,
 np.int64(121): 416,
 np.int64(133): 414,
 np.int64(135): 410,
 np.int64(26453): 408,
 np.int64(114): 402,
 np.int64(142): 391,
 np.int64(26434): 390,
 np.int64(138): 389,
 np.int64(139): 386,
 np.int64(130): 386,
 np.int64(145): 385,
 np.int64(124): 374,
 np.int64(26466): 370,
 np.int64(127): 370,
 np.int64(26485): 369,
 np.int64(131): 364,
 np.int64(26469): 362,
 np.int64(26479): 359,
 np.int64(141): 358,
 np.int64(26495): 355,
 np.int64(26463): 355,
 np.int64(26498): 354,
 np.int64(152): 350,
 np.int64(149): 349,
 np.int64(148): 346,
 np.int64(140): 345,
 np.int64(155): 345,
 np.int64(151): 339,
 np.int64(158): 339,
 np.int64(26450): 330,
 np.int64(137): 326,
 np.int64(26518): 326,
 np.int64(146): 325,
 np.int64(26544): 322,
 np.int64(26590): 320,
 np.int64(162): 319,
 np.int64(26629): 317,
 np.int64(161): 314,
 np.int64(26476): 314,
 np.int64(26488): 313,
 np.int64(156): 312,
 np.int64(26515): 310,
 np.int64(26616): 309,
 np.int64(26554): 309,
 np.int64(26508): 306,
 np.int64(144): 304,
 np.int64(26445): 302,
 np.int64(26646): 302,
 np.int64(26521): 300,
 np.int64(26570): 300,
 np.int64(143): 298,
 np.int64(134): 296,
 np.int64(171): 296,
 np.int64(168): 291,
 np.int64(26528): 290,
 np.int64(26432): 290,
 np.int64(165): 289,
 np.int64(26600): 286,
 np.int64(26531): 285,
 np.int64(26448): 285,
 np.int64(175): 284,
 np.int64(26567): 284,
 np.int64(26431): 281,
 np.int64(26511): 281,
 np.int64(26478): 281,
 np.int64(26455): 280,
 np.int64(26534): 280,
 np.int64(26541): 280,
 np.int64(174): 279,
 np.int64(159): 278,
 np.int64(181): 278,
 np.int64(154): 278,
 np.int64(26505): 276,
 np.int64(172): 275,
 np.int64(147): 273,
 np.int64(26444): 269,
 np.int64(26442): 269,
 np.int64(164): 266,
 np.int64(26501): 265,
 np.int64(26564): 264,
 np.int64(26642): 262,
 np.int64(184): 262,
 np.int64(26447): 262,
 np.int64(26577): 262,
 np.int64(26538): 262,
 np.int64(26458): 261,
 np.int64(26491): 261,
 np.int64(26465): 260,
 np.int64(150): 260,
 np.int64(26547): 258,
 np.int64(26473): 256,
 np.int64(191): 255,
 np.int64(26560): 254,
 np.int64(26610): 251,
 np.int64(26636): 249,
 np.int64(26486): 248,
 np.int64(26639): 247,
 np.int64(26606): 245,
 np.int64(26441): 243,
 np.int64(157): 243,
 np.int64(26580): 242,
 np.int64(153): 241,
 np.int64(26596): 241,
 np.int64(188): 240,
 np.int64(26548): 240,
 np.int64(26483): 240,
 np.int64(26468): 239,
 np.int64(185): 239,
 np.int64(194): 239,
 np.int64(169): 238,
 np.int64(26475): 238,
 np.int64(26682): 238,
 np.int64(26489): 238,
 np.int64(178): 237,
 np.int64(26525): 236,
 np.int64(160): 236,
 np.int64(26619): 236,
 np.int64(167): 235,
 np.int64(177): 234,
 np.int64(26551): 233,
 np.int64(26599): 233,
 np.int64(26477): 231,
 np.int64(26514): 230,
 np.int64(26517): 229,
 np.int64(26499): 229,
 np.int64(26648): 229,
 np.int64(26561): 229,
 np.int64(26550): 228,
 np.int64(26481): 228,
 np.int64(26659): 228,
 np.int64(26655): 227,
 np.int64(26632): 227,
 np.int64(173): 226,
 np.int64(26644): 226,
 np.int64(182): 226,
 np.int64(26503): 226,
 np.int64(187): 224,
 np.int64(26584): 223,
 np.int64(26842): 223,
 np.int64(26492): 221,
 np.int64(190): 221,
 np.int64(26662): 220,
 np.int64(26460): 219,
 np.int64(26524): 218,
 np.int64(26574): 218,
 np.int64(201): 218,
 np.int64(166): 218,
 np.int64(210): 217,
 np.int64(26557): 213,
 np.int64(195): 213,
 np.int64(26535): 213,
 np.int64(180): 213,
 np.int64(26678): 213,
 np.int64(26494): 212,
 np.int64(26493): 211,
 np.int64(26467): 210,
 np.int64(26652): 210,
 np.int64(26597): 210,
 np.int64(26527): 209,
 np.int64(163): 209,
 np.int64(26472): 209,
 np.int64(207): 208,
 np.int64(204): 207,
 np.int64(192): 207,
 np.int64(26698): 206,
 np.int64(26510): 206,
 np.int64(26688): 206,
 np.int64(26474): 206,
 np.int64(26822): 204,
 np.int64(26626): 204,
 np.int64(26685): 203,
 np.int64(26540): 203,
 np.int64(198): 202,
 np.int64(26630): 202,
 np.int64(197): 202,
 np.int64(26645): 202,
 np.int64(170): 202,
 np.int64(26669): 202,
 np.int64(26587): 201,
 np.int64(26593): 201,
 np.int64(26537): 200,
 np.int64(200): 200,
 np.int64(26496): 200,
 np.int64(26832): 200,
 np.int64(26589): 199,
 np.int64(26457): 199,
 np.int64(26631): 198,
 np.int64(26609): 198,
 np.int64(211): 198,
 np.int64(26504): 197,
 np.int64(26461): 197,
 np.int64(26656): 196,
 np.int64(179): 196,
 np.int64(26462): 196,
 np.int64(26672): 196,
 np.int64(26665): 194,
 np.int64(183): 194,
 np.int64(214): 194,
 np.int64(26586): 194,
 np.int64(26480): 194,
 np.int64(26482): 193,
 np.int64(26691): 193,
 np.int64(26470): 192,
 np.int64(224): 189,
 np.int64(26452): 189,
 np.int64(186): 188,
 np.int64(26464): 187,
 np.int64(26675): 187,
 np.int64(26506): 185,
 np.int64(26635): 185,
 np.int64(26658): 185,
 np.int64(26502): 184,
 np.int64(26819): 184,
 np.int64(26681): 183,
 np.int64(208): 182,
 np.int64(26711): 182,
 np.int64(26451): 182,
 np.int64(26549): 182,
 np.int64(26583): 182,
 np.int64(206): 181,
 np.int64(26594): 180,
 np.int64(26530): 179,
 np.int64(26622): 179,
 np.int64(26836): 179,
 np.int64(203): 179,
 np.int64(26604): 179,
 np.int64(26747): 178,
 np.int64(26509): 178,
 np.int64(220): 178,
 np.int64(189): 178,
 np.int64(26558): 176,
 np.int64(26649): 176,
 np.int64(26871): 176,
 np.int64(26579): 176,
 np.int64(26620): 176,
 np.int64(221): 175,
 np.int64(26546): 175,
 np.int64(218): 175,
 np.int64(26612): 175,
 np.int64(26591): 175,
 np.int64(205): 175,
 np.int64(26471): 174,
 np.int64(26487): 174,
 np.int64(26623): 173,
 np.int64(26806): 173,
 np.int64(26563): 172,
 np.int64(230): 172,
 np.int64(26839): 172,
 np.int64(26763): 172,
 np.int64(26695): 171,
 np.int64(26661): 170,
 np.int64(26829): 170,
 np.int64(26602): 170,
 np.int64(193): 169,
 np.int64(176): 168,
 np.int64(26559): 168,
 np.int64(26783): 168,
 np.int64(26571): 168,
 np.int64(216): 167,
 np.int64(217): 166,
 np.int64(227): 166,
 np.int64(26816): 166,
 np.int64(26607): 165,
 np.int64(26545): 164,
 np.int64(26705): 163,
 np.int64(26500): 163,
 np.int64(26526): 163,
 np.int64(26555): 163,
 np.int64(26507): 162,
 np.int64(233): 162,
 np.int64(26862): 162,
 np.int64(26868): 161,
 np.int64(26773): 161,
 np.int64(26513): 161,
 np.int64(26605): 161,
 np.int64(26671): 161,
 np.int64(26618): 160,
 np.int64(231): 160,
 np.int64(26826): 160,
 np.int64(26750): 160,
 np.int64(26581): 159,
 np.int64(26595): 159,
 np.int64(26523): 158,
 np.int64(26490): 158,
 np.int64(26454): 156,
 np.int64(26701): 156,
 np.int64(26770): 155,
 np.int64(213): 155,
 np.int64(26573): 154,
 np.int64(26516): 154,
 np.int64(223): 154,
 np.int64(26512): 154,
 np.int64(26721): 153,
 np.int64(26529): 153,
 np.int64(26519): 153,
 np.int64(26625): 153,
 np.int64(26533): 152,
 np.int64(26874): 152,
 np.int64(26522): 152,
 np.int64(26852): 152,
 np.int64(202): 152,
 np.int64(26737): 151,
 np.int64(26576): 151,
 np.int64(26484): 150,
 np.int64(26638): 150,
 np.int64(26835): 150,
 np.int64(26543): 149,
 np.int64(26692): 149,
 np.int64(26865): 149,
 np.int64(26634): 148,
 np.int64(26628): 148,
 np.int64(26793): 148,
 np.int64(26603): 148,
 np.int64(215): 147,
 np.int64(26601): 147,
 np.int64(26614): 146,
 np.int64(26849): 146,
 np.int64(26585): 146,
 np.int64(26700): 146,
 np.int64(26823): 146,
 np.int64(234): 145,
 np.int64(26566): 145,
 np.int64(26569): 145,
 np.int64(26598): 145,
 np.int64(26790): 145,
 np.int64(240): 145,
 np.int64(26520): 144,
 np.int64(26592): 144,
 np.int64(26901): 144,
 np.int64(26568): 143,
 np.int64(26539): 143,
 np.int64(26613): 143,
 np.int64(26878): 143,
 np.int64(26627): 143,
 np.int64(26861): 142,
 np.int64(26565): 142,
 np.int64(26666): 142,
 np.int64(219): 142,
 np.int64(26633): 142,
 np.int64(26894): 142,
 np.int64(26679): 142,
 np.int64(26657): 141,
 np.int64(26641): 141,
 np.int64(222): 140,
 np.int64(26536): 140,
 np.int64(26617): 139,
 np.int64(26881): 139,
 np.int64(26838): 138,
 np.int64(26904): 138,
 np.int64(26776): 138,
 np.int64(26608): 138,
 np.int64(26855): 137,
 np.int64(237): 137,
 np.int64(250): 137,
 np.int64(26741): 137,
 np.int64(199): 137,
 np.int64(26556): 136,
 np.int64(26647): 136,
 np.int64(26668): 136,
 np.int64(26891): 136,
 np.int64(247): 135,
 np.int64(26690): 135,
 np.int64(26786): 135,
 np.int64(26718): 135,
 np.int64(26654): 134,
 np.int64(196): 134,
 np.int64(236): 133,
 np.int64(226): 133,
 np.int64(26621): 132,
 np.int64(26858): 132,
 np.int64(26615): 132,
 np.int64(228): 131,
 np.int64(26757): 131,
 np.int64(256): 131,
 np.int64(259): 131,
 np.int64(26872): 131,
 np.int64(26898): 131,
 np.int64(246): 130,
 np.int64(26744): 129,
 np.int64(26497): 128,
 np.int64(212): 128,
 np.int64(26715): 128,
 np.int64(26687): 128,
 np.int64(209): 128,
 np.int64(26760): 127,
 np.int64(26680): 127,
 np.int64(26792): 127,
 np.int64(26643): 127,
 np.int64(225): 127,
 np.int64(26582): 126,
 np.int64(244): 126,
 np.int64(26780): 126,
 np.int64(26887): 126,
 np.int64(243): 126,
 np.int64(26907): 126,
 np.int64(26640): 125,
 np.int64(26588): 125,
 np.int64(26845): 125,
 np.int64(26731): 124,
 np.int64(241): 124,
 np.int64(26743): 124,
 np.int64(26708): 124,
 np.int64(26667): 124,
 np.int64(26704): 124,
 np.int64(26689): 124,
 np.int64(26717): 123,
 np.int64(26767): 123,
 np.int64(26575): 122,
 np.int64(26660): 122,
 np.int64(26851): 122,
 np.int64(26624): 122,
 np.int64(26748): 122,
 np.int64(26856): 122,
 np.int64(26562): 121,
 np.int64(26684): 121,
 np.int64(254): 121,
 np.int64(26686): 121,
 np.int64(229): 121,
 np.int64(251): 121,
 np.int64(242): 120,
 np.int64(263): 120,
 np.int64(253): 120,
 np.int64(26553): 120,
 np.int64(26825): 119,
 np.int64(255): 119,
 np.int64(26740): 118,
 np.int64(239): 118,
 np.int64(26611): 118,
 np.int64(26884): 118,
 np.int64(26848): 118,
 np.int64(26914): 118,
 np.int64(266): 118,
 np.int64(26766): 116,
 np.int64(26888): 116,
 np.int64(26749): 116,
 np.int64(269): 115,
 np.int64(238): 115,
 np.int64(26697): 115,
 np.int64(235): 114,
 np.int64(26677): 114,
 np.int64(26578): 114,
 np.int64(248): 113,
 np.int64(26694): 113,
 np.int64(260): 113,
 np.int64(26876): 113,
 np.int64(26846): 112,
 np.int64(26532): 112,
 np.int64(26863): 112,
 np.int64(272): 112,
 np.int64(26745): 112,
 np.int64(26777): 111,
 np.int64(26833): 111,
 np.int64(276): 111,
 np.int64(26864): 110,
 np.int64(26542): 110,
 np.int64(280): 110,
 np.int64(26637): 109,
 np.int64(26873): 109,
 np.int64(26812): 109,
 np.int64(232): 109,
 np.int64(279): 109,
 np.int64(26834): 109,
 np.int64(249): 108,
 np.int64(26552): 108,
 np.int64(26714): 108,
 np.int64(26796): 108,
 np.int64(26702): 108,
 np.int64(26746): 107,
 np.int64(26847): 107,
 np.int64(26779): 106,
 np.int64(275): 105,
 np.int64(26821): 105,
 np.int64(26650): 105,
 np.int64(245): 104,
 np.int64(26831): 104,
 np.int64(26875): 104,
 np.int64(26813): 104,
 np.int64(26572): 104,
 np.int64(26727): 104,
 np.int64(257): 103,
 np.int64(26676): 103,
 np.int64(26869): 103,
 np.int64(26683): 103,
 np.int64(26809): 103,
 np.int64(26893): 102,
 np.int64(26653): 102,
 np.int64(26830): 101,
 np.int64(26699): 101,
 np.int64(270): 101,
 np.int64(26802): 101,
 np.int64(26854): 101,
 np.int64(26651): 101,
 np.int64(26882): 101,
 np.int64(26769): 100,
 np.int64(26870): 99,
 np.int64(26837): 99,
 np.int64(26753): 99,
 np.int64(26817): 99,
 np.int64(26754): 99,
 np.int64(26789): 99,
 np.int64(26799): 99,
 np.int64(264): 98,
 np.int64(26782): 98,
 np.int64(26840): 98,
 np.int64(26917): 98,
 np.int64(26828): 98,
 np.int64(26820): 98,
 np.int64(271): 98,
 np.int64(26756): 97,
 np.int64(26841): 97,
 np.int64(26738): 97,
 np.int64(26803): 96,
 np.int64(26877): 96,
 np.int64(26670): 96,
 np.int64(267): 95,
 np.int64(26713): 95,
 np.int64(26843): 95,
 np.int64(26911): 95,
 np.int64(26908): 94,
 np.int64(26696): 94,
 np.int64(252): 94,
 np.int64(26775): 94,
 np.int64(262): 94,
 np.int64(26664): 94,
 np.int64(26859): 94,
 np.int64(26762): 93,
 np.int64(26707): 93,
 np.int64(26706): 93,
 np.int64(26735): 93,
 np.int64(26850): 93,
 np.int64(26860): 93,
 np.int64(26885): 93,
 np.int64(26725): 93,
 np.int64(26866): 92,
 np.int64(265): 92,
 np.int64(26734): 92,
 np.int64(26903): 92,
 np.int64(26857): 92,
 np.int64(26867): 91,
 np.int64(26739): 91,
 np.int64(277): 91,
 np.int64(26772): 90,
 np.int64(26768): 90,
 np.int64(26824): 90,
 np.int64(286): 89,
 np.int64(26710): 89,
 np.int64(26761): 88,
 np.int64(26883): 88,
 np.int64(283): 88,
 np.int64(273): 87,
 np.int64(26712): 87,
 np.int64(26937): 87,
 np.int64(26890): 87,
 np.int64(290): 87,
 np.int64(26724): 87,
 np.int64(26663): 87,
 np.int64(26787): 86,
 np.int64(26853): 86,
 np.int64(26765): 86,
 np.int64(26897): 86,
 np.int64(26720): 86,
 np.int64(26800): 85,
 np.int64(302): 84,
 np.int64(26810): 84,
 np.int64(26716): 84,
 np.int64(26774): 84,
 np.int64(26742): 83,
 np.int64(26781): 83,
 np.int64(285): 83,
 np.int64(278): 82,
 np.int64(289): 82,
 np.int64(295): 82,
 np.int64(26880): 82,
 np.int64(26815): 81,
 np.int64(292): 81,
 np.int64(26719): 81,
 np.int64(26940): 81,
 np.int64(288): 80,
 np.int64(261): 80,
 np.int64(316): 80,
 np.int64(26889): 80,
 np.int64(282): 80,
 np.int64(284): 79,
 np.int64(26892): 79,
 np.int64(305): 79,
 np.int64(309): 79,
 np.int64(26886): 79,
 np.int64(26764): 78,
 np.int64(26674): 78,
 np.int64(26896): 78,
 np.int64(26844): 78,
 np.int64(26726): 78,
 np.int64(308): 78,
 np.int64(303): 78,
 np.int64(258): 78,
 np.int64(26785): 77,
 np.int64(321): 77,
 np.int64(26920): 77,
 np.int64(296): 77,
 np.int64(26751): 77,
 np.int64(26673): 76,
 np.int64(26923): 76,
 np.int64(26693): 76,
 np.int64(26879): 76,
 np.int64(26900): 76,
 np.int64(287): 75,
 np.int64(26709): 75,
 np.int64(313): 75,
 np.int64(299): 75,
 np.int64(26733): 75,
 np.int64(26759): 75,
 np.int64(26791): 75,
 np.int64(298): 75,
 np.int64(322): 74,
 np.int64(26930): 74,
 np.int64(291): 74,
 np.int64(26771): 74,
 np.int64(315): 74,
 np.int64(311): 74,
 np.int64(332): 72,
 np.int64(26755): 72,
 np.int64(26913): 72,
 np.int64(26758): 71,
 np.int64(26895): 71,
 np.int64(26778): 71,
 np.int64(318): 71,
 np.int64(26723): 70,
 np.int64(26808): 70,
 np.int64(26924): 70,
 np.int64(325): 70,
 np.int64(26818): 70,
 np.int64(328): 69,
 np.int64(26728): 69,
 np.int64(281): 69,
 np.int64(26730): 68,
 np.int64(26814): 68,
 np.int64(26795): 68,
 np.int64(26910): 68,
 np.int64(26736): 67,
 np.int64(26752): 67,
 np.int64(274): 67,
 np.int64(26899): 67,
 np.int64(293): 66,
 np.int64(26801): 66,
 np.int64(26788): 66,
 np.int64(300): 65,
 np.int64(268): 65,
 np.int64(26921): 65,
 np.int64(26934): 64,
 np.int64(26906): 64,
 np.int64(301): 64,
 np.int64(307): 64,
 np.int64(329): 64,
 np.int64(26827): 63,
 np.int64(306): 63,
 np.int64(26902): 62,
 np.int64(319): 62,
 np.int64(26933): 62,
 np.int64(26794): 62,
 np.int64(26918): 61,
 np.int64(26916): 61,
 np.int64(26722): 61,
 np.int64(26807): 61,
 np.int64(26784): 60,
 np.int64(312): 59,
 np.int64(294): 59,
 np.int64(26919): 59,
 np.int64(26732): 59,
 np.int64(338): 58,
 np.int64(335): 58,
 np.int64(345): 58,
 np.int64(26703): 57,
 np.int64(304): 57,
 np.int64(26811): 57,
 np.int64(297): 56,
 np.int64(334): 56,
 np.int64(352): 56,
 np.int64(26797): 55,
 np.int64(26804): 55,
 np.int64(26931): 55,
 np.int64(26798): 54,
 np.int64(351): 54,
 np.int64(26912): 54,
 np.int64(26905): 54,
 np.int64(26922): 53,
 np.int64(368): 53,
 np.int64(324): 52,
 np.int64(26729): 52,
 np.int64(360): 52,
 np.int64(26909): 52,
 np.int64(310): 52,
 np.int64(326): 51,
 np.int64(336): 50,
 np.int64(339): 50,
 np.int64(364): 50,
 np.int64(331): 50,
 np.int64(355): 49,
 np.int64(320): 49,
 np.int64(347): 49,
 np.int64(337): 49,
 np.int64(342): 49,
 np.int64(348): 47,
 np.int64(372): 47,
 np.int64(26936): 47,
 np.int64(26927): 46,
 np.int64(349): 45,
 np.int64(26932): 45,
 np.int64(354): 45,
 np.int64(381): 45,
 np.int64(344): 44,
 np.int64(340): 44,
 np.int64(323): 44,
 np.int64(358): 44,
 np.int64(341): 43,
 np.int64(26939): 43,
 np.int64(314): 42,
 np.int64(374): 42,
 np.int64(361): 41,
 np.int64(26941): 41,
 np.int64(26929): 41,
 np.int64(333): 40,
 np.int64(26943): 40,
 np.int64(26915): 39,
 np.int64(330): 39,
 np.int64(346): 38,
 np.int64(380): 38,
 np.int64(327): 38,
 np.int64(359): 38,
 np.int64(373): 37,
 np.int64(317): 37,
 np.int64(363): 37,
 np.int64(403): 37,
 np.int64(388): 37,
 np.int64(371): 37,
 np.int64(26938): 37,
 np.int64(401): 37,
 np.int64(410): 36,
 np.int64(350): 36,
 np.int64(357): 36,
 np.int64(365): 36,
 np.int64(26805): 36,
 np.int64(26946): 35,
 np.int64(385): 35,
 np.int64(369): 35,
 np.int64(392): 35,
 np.int64(394): 35,
 np.int64(378): 35,
 np.int64(367): 34,
 np.int64(399): 33,
 np.int64(353): 32,
 np.int64(382): 32,
 np.int64(362): 32,
 np.int64(396): 32,
 np.int64(405): 31,
 np.int64(390): 31,
 np.int64(366): 31,
 np.int64(375): 31,
 np.int64(430): 31,
 np.int64(356): 30,
 np.int64(343): 30,
 np.int64(408): 30,
 np.int64(398): 30,
 np.int64(370): 29,
 np.int64(412): 29,

In [25]:
##Booking time different in hours
df['booking_time_diff_hr'].value_counts().to_dict()

{np.int64(0): 8122715,
 np.int64(1): 55991,
 np.int64(440): 23791,
 np.int64(2): 19758,
 np.int64(441): 14077,
 np.int64(442): 11594,
 np.int64(443): 11055,
 np.int64(3): 10619,
 np.int64(444): 9319,
 np.int64(447): 7360,
 np.int64(445): 6195,
 np.int64(446): 5964,
 np.int64(4): 5906,
 np.int64(448): 4654,
 np.int64(5): 3314,
 np.int64(6): 1867,
 np.int64(7): 808,
 np.int64(449): 265,
 np.int64(8): 130}

### We observe that there are 8315382 - 3248768 = 50,66,614 booking that happen in less than 1 hour of request by a user

In [26]:
len(df)

8315382

In [27]:
### Handling Case 1: Re-booking Again to Same Location within 1hour by same user

df = df[~((df.duplicated(subset=['number','pick_lat','pick_lng'],keep=False)) & (df.booking_time_diff_hr<=1))]

In [28]:
## Before removing Row Count
len(df)

3248768

###  Removed 5066614 rows in `Case1` we now have 3248768

In [29]:
df.to_csv('C:/Sachin/project/Bike-Taxi-Rides-Request-Demand-Forecast/data/preprocessed/preprocessed_2.csv',index = False, compression = 'gzip')

### Handling Case2: One user Books rides are different lat-long within 8mins time (ride time + driver arrival time)
#### Fraud User
#### Human error booking

In [30]:
df = pd.read_csv('C:/Sachin/project/Bike-Taxi-Rides-Request-Demand-Forecast/data/preprocessed/preprocessed_2.csv', compression = 'gzip')

In [31]:
df.shape

(3248768, 16)

In [32]:
print("Number of rides booked by same customer within 8mins time: {}".format(len(df[(df.booking_time_diff_min<8)])))
df = df[(df.booking_time_diff_min>=8)]

Number of rides booked by same customer within 8mins time: 2697418

### Assuming earth as ellipsoids, calculating geodesic distance b/w pickup and drop latitude and longitude

The geodesic distance is the shortest distance on the surface of an ellipsoidal model of the earth.

In [33]:
%%time
def geodestic_distance(pick_lat, pick_lng, drop_lat, drop_lng):
    # 1mile = 1.60934 Kms
    return round(geodesic((pick_lat, pick_lng), (drop_lat, drop_lng)).miles*1.60934,2)

df['geodesic_distance'] = np.vectorize(geodestic_distance)(df['pick_lat'],df['pick_lng'],df['drop_lat'],df['drop_lng'])

CPU times: total: 32.1 s
Wall time: 32.4 s

##### Number of rides booked but same customer within 8mins time: 2697418

In [34]:
df[df['geodesic_distance']<=0.5]['geodesic_distance'].value_counts()

geodesic_distance
0.00    2192
0.01     551
0.02     360
0.03     248
0.50     206
0.48     175
0.04     173
0.49     170
0.05     161
0.45     157
0.39     156
0.46     151
0.47     139
0.42     138
0.43     134
0.44     133
0.06     126
0.40     124
0.07     124
0.35     118
0.41     115
0.36     113
0.09     111
0.12     110
0.38     105
0.30     105
0.34     104
0.37     104
0.33     102
0.26      96
0.14      96
0.10      96
0.08      94
0.31      93
0.32      93
0.24      91
0.17      87
0.27      85
0.28      84
0.13      83
0.22      81
0.29      81
0.11      79
0.23      77
0.21      77
0.18      75
0.15      70
0.20      70
0.25      64
0.19      63
0.16      56
Name: count, dtype: int64

### Handle Case 2.1: Removing ride request less than 0.05 miles = 50meters

In [35]:
print("Number of Rides Requests less than 50meters: {}".format(len(df[df.geodesic_distance<=0.05])))

Number of Rides Requests less than 50meters: 3685

In [36]:
df = df[df.geodesic_distance>0.05]
df

,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,mins,hour,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
0,2020-10-10 07:34:16,-1,12.975773,77.571070,12.878468,77.445330,34,7,10,10,2020,5,1602315,0,445,26705,17.38
1,2020-10-30 09:00:44,-1,12.945731,77.622500,12.973030,77.616840,0,9,30,10,2020,4,1604048,1602870,0,19,3.08
2,2020-11-27 20:16:20,-1,13.031985,77.571280,12.960211,77.646910,16,20,27,11,2020,4,1606508,1604048,0,41,11.42
4,2020-12-05 22:09:55,-1,12.938531,77.578940,12.952660,77.568825,9,22,5,12,2020,5,1607206,1606509,0,11,1.91
8,2020-12-17 17:40:20,-1,12.979331,77.577910,12.944552,77.596510,40,17,17,12,2020,3,1608226,1607418,0,13,4.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3248756,2020-11-23 12:51:56,99999,13.042774,77.609170,13.059187,77.596280,51,12,23,11,2020,0,1606135,1602266,1,64,2.29
3248758,2021-01-11 17:45:09,99999,13.059011,77.596270,13.042389,77.611790,45,17,11,1,2021,0,1610387,1606814,0,59,2.49
3248761,2021-02-07 09:10:15,99999,12.956661,77.521935,12.925382,77.686516,10,9,7,2,2021,6,1612689,1610568,0,35,18.19
3248764,2021-02-19 20:43:25,99999,13.029296,77.592580,12.927923,77.627106,43,20,19,2,2021,4,1613767,1613158,0,10,11.82
3248766,2021-02-27 08:26:23,99999,12.956665,77.521870,12.948099,77.562990,26,8,27,2,2021,5,1614414,1613842,0,9,4.56

In [37]:
len(df)

547665

In [38]:
df.to_csv('C:/Sachin/project/Bike-Taxi-Rides-Request-Demand-Forecast/data/preprocessed/preprocessed_3.csv',index = False, compression = 'gzip')

In [39]:
import time
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderUnavailable

geolocator = Nominatim(user_agent="my_app", timeout=20)

places = ["India", "Bengaluru, Karnataka, India", "Karnataka, India"]

for place in places:
    try:
        loc = geolocator.geocode(place, exactly_one=True, addressdetails=True)
        if loc:
            print(place, loc.raw.get("boundingbox"))
        else:
            print(place, "No result")
    except (GeocoderTimedOut, GeocoderUnavailable) as e:
        print(place, f"Failed: {e}")
    time.sleep(1)

India ['6.5531169', '35.6729307', '67.9544415', '97.3950905']
Bengaluru, Karnataka, India ['12.8334905', '13.1426196', '77.4598797', '77.7840639']
Karnataka, India ['11.5945587', '18.4766494', '74.0543908', '78.5875761']

### Handle Case3: Rides request in non-operational regions
OLA Bikes OPERATION CITY (Bangalore)

### Ride requests due to some bug or crash in app.
<hr>

#### India: 'boundingbox': ['6.5531169', '35.6729307', '67.9544415', '97.3950905']
#### Bangalore:'boundingbox': ['12.8334905', '13.1426196', '77.4598797', '77.7840639']
#### Karnataka: 'boundingbox': ['11.5945587', '18.4766494', '74.0543908', '78.5875761']

In [40]:
df = pd.read_csv('C:/Sachin/project/Bike-Taxi-Rides-Request-Demand-Forecast/data/preprocessed/preprocessed_3.csv', compression = 'gzip')
location = geolocator.geocode("India")
location.raw

{'place_id': 250717345,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. http://osm.org/copyright',
 'osm_type': 'relation',
 'osm_id': 304716,
 'lat': '22.3511148',
 'lon': '78.6677428',
 'class': 'boundary',
 'type': 'administrative',
 'place_rank': 4,
 'importance': 0.8910953652546315,
 'addresstype': 'country',
 'name': 'India',
 'display_name': 'India',
 'boundingbox': ['6.5531169', '35.6729307', '67.9544415', '97.3950905']}

In [41]:
df

,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,mins,hour,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
0,2020-10-10 07:34:16,-1,12.975773,77.571070,12.878468,77.445330,34,7,10,10,2020,5,1602315,0,445,26705,17.38
1,2020-10-30 09:00:44,-1,12.945731,77.622500,12.973030,77.616840,0,9,30,10,2020,4,1604048,1602870,0,19,3.08
2,2020-11-27 20:16:20,-1,13.031985,77.571280,12.960211,77.646910,16,20,27,11,2020,4,1606508,1604048,0,41,11.42
3,2020-12-05 22:09:55,-1,12.938531,77.578940,12.952660,77.568825,9,22,5,12,2020,5,1607206,1606509,0,11,1.91
4,2020-12-17 17:40:20,-1,12.979331,77.577910,12.944552,77.596510,40,17,17,12,2020,3,1608226,1607418,0,13,4.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547660,2020-11-23 12:51:56,99999,13.042774,77.609170,13.059187,77.596280,51,12,23,11,2020,0,1606135,1602266,1,64,2.29
547661,2021-01-11 17:45:09,99999,13.059011,77.596270,13.042389,77.611790,45,17,11,1,2021,0,1610387,1606814,0,59,2.49
547662,2021-02-07 09:10:15,99999,12.956661,77.521935,12.925382,77.686516,10,9,7,2,2021,6,1612689,1610568,0,35,18.19
547663,2021-02-19 20:43:25,99999,13.029296,77.592580,12.927923,77.627106,43,20,19,2,2021,4,1613767,1613158,0,10,11.82
547664,2021-02-27 08:26:23,99999,12.956665,77.521870,12.948099,77.562990,26,8,27,2,2021,5,1614414,1613842,0,9,4.56

In [42]:
## How many rides outside india?
df[(df.pick_lat<=6.5531169) | (df.pick_lat>=35.6729307) | (df.pick_lng<=67.9544415) | (df.pick_lng>=97.3950905) | (df.pick_lat<=6.5531169) | (df.pick_lat>=35.6729307) | (df.pick_lng<=67.9544415) | (df.pick_lng>=97.3950905)]

,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,mins,hour,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
23994,2020-08-30 18:40:45,4133,6.525380,38.829945,12.983918,77.538660,40,18,30,8,2020,6,1598812,1597404,0,23,4301.97
38696,2021-01-03 21:07:04,6783,67.696650,-0.658846,13.032407,77.604744,7,21,3,1,2021,6,1609708,1609076,0,10,8176.72
91252,2020-12-30 10:29:19,16181,0.000000,0.000000,12.828831,77.588000,29,10,30,12,2020,2,1609324,1608143,0,19,8670.97
189599,2020-12-29 12:24:17,33876,0.000000,0.000000,12.989280,77.619330,24,12,29,12,2020,1,1609244,1608328,0,15,8675.22
195746,2020-12-27 09:23:26,34958,0.000000,0.000000,12.934451,77.611320,23,9,27,12,2020,6,1609061,1593632,4,257,8674.06
199809,2020-11-24 18:27:12,35688,0.000000,0.000000,12.946287,77.580060,27,18,24,11,2020,1,1606242,0,446,26770,8670.73
407129,2020-11-23 07:55:26,73993,0.000000,0.000000,20.355660,85.815950,55,7,23,11,2020,0,1606118,0,446,26768,9579.89
471181,2020-04-26 18:11:48,85865,28.375704,19.159657,13.022936,77.551570,11,18,26,4,2020,6,1587924,1586205,0,28,6255.52

In [43]:
df_outside_india = df[
    (df.pick_lat <= 6.2325274) |
    (df.pick_lat >= 35.6745457) |
    (df.pick_lng <= 68.1113787) |
    (df.pick_lng >= 97.395561) |
    (df.drop_lat <= 6.2325274) |
    (df.drop_lat >= 35.6745457) |
    (df.drop_lng <= 68.1113787) |
    (df.drop_lng >= 97.395561)
]

df_outside_india.shape

(146, 17)

### OLA Bikes is only operational in India
### Removing all rides for which pickup or drop is outside INDIA.
#### Number of such cases: 146

In [44]:
df.reset_index(inplace = True, drop = True)
df_outside_india = df[
    (df.pick_lat <= 6.2325274) |
    (df.pick_lat >= 35.6745457) |
    (df.pick_lng <= 68.1113787) |
    (df.pick_lng >= 97.395561) |
    (df.drop_lat <= 6.2325274) |
    (df.drop_lat >= 35.6745457) |
    (df.drop_lng <= 68.1113787) |
    (df.drop_lng >= 97.395561)
]
df = df[~df.index.isin(df_outside_india.index)].reset_index(drop = True)

In [45]:
df

,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,mins,hour,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
0,2020-10-10 07:34:16,-1,12.975773,77.571070,12.878468,77.445330,34,7,10,10,2020,5,1602315,0,445,26705,17.38
1,2020-10-30 09:00:44,-1,12.945731,77.622500,12.973030,77.616840,0,9,30,10,2020,4,1604048,1602870,0,19,3.08
2,2020-11-27 20:16:20,-1,13.031985,77.571280,12.960211,77.646910,16,20,27,11,2020,4,1606508,1604048,0,41,11.42
3,2020-12-05 22:09:55,-1,12.938531,77.578940,12.952660,77.568825,9,22,5,12,2020,5,1607206,1606509,0,11,1.91
4,2020-12-17 17:40:20,-1,12.979331,77.577910,12.944552,77.596510,40,17,17,12,2020,3,1608226,1607418,0,13,4.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547514,2020-11-23 12:51:56,99999,13.042774,77.609170,13.059187,77.596280,51,12,23,11,2020,0,1606135,1602266,1,64,2.29
547515,2021-01-11 17:45:09,99999,13.059011,77.596270,13.042389,77.611790,45,17,11,1,2021,0,1610387,1606814,0,59,2.49
547516,2021-02-07 09:10:15,99999,12.956661,77.521935,12.925382,77.686516,10,9,7,2,2021,6,1612689,1610568,0,35,18.19
547517,2021-02-19 20:43:25,99999,13.029296,77.592580,12.927923,77.627106,43,20,19,2,2021,4,1613767,1613158,0,10,11.82
547518,2021-02-27 08:26:23,99999,12.956665,77.521870,12.948099,77.562990,26,8,27,2,2021,5,1614414,1613842,0,9,4.56

In [46]:
print("Number of Good Ride Requests: {}".format(len(df)))

Number of Good Ride Requests: 547519

In [47]:
## How many pickups and drops are outside bangalore?
# ['12.8334905', '13.1426196', '77.4598797', '77.7840639']
pck_outside_bng = df[(df.pick_lat<=12.8334905) | (df.pick_lat>=13.1426196) | (df.pick_lng<=77.4598797) | (df.pick_lng>=77.7840639)]
drp_outside_bng = df[(df.drop_lat<=12.8334905) | (df.drop_lat>=13.1426196) | (df.drop_lng<=77.4598797) | (df.drop_lng>=77.7840639)]
print("Number of Pickup Requests Outside Bangalore: ",len(pck_outside_bng))
print("Number of Customers pickup outside Bangalore: ",len(np.unique(pck_outside_bng['number'].values)))

print("Number of Drops Requests Outside Bangalore: ",len(drp_outside_bng))
print("Number of Customers Drop outside Bangalore: ",len(np.unique(drp_outside_bng['number'].values)))

Number of Pickup Requests Outside Bangalore:  30930
Number of Customers pickup outside Bangalore:  14309
Number of Drops Requests Outside Bangalore:  34321
Number of Customers Drop outside Bangalore:  17079

In [48]:
### Bounding PickUp Lat-Long Within State Karnataka
# ['11.5945587', '18.4766494', '74.0543908', '78.5875761']
pck_outside_KA = df[(df.pick_lat<=11.5945587) | (df.pick_lat>=18.4766494) | (df.pick_lng<=74.0543908) | (df.pick_lng>=78.5875761)]
drp_outside_KA = df[(df.drop_lat<=11.5945587) | (df.drop_lat>=18.4766494) | (df.drop_lng<=74.0543908) | (df.drop_lng>=78.5875761)]
print("Pickups Outisde KA: {} \nDrop outside KA: {}".format(len(pck_outside_KA),len(drp_outside_KA)))
print("Number of Customers Drop outside KA: ",len(np.unique(drp_outside_KA['number'].values)))
print("Number of Customers pickup outside KA: ",len(np.unique(pck_outside_KA['number'].values)))

Pickups Outisde KA: 6773
Drop outside KA: 7039
Number of Customers Drop outside KA:  4278
Number of Customers pickup outside KA:  4028

In [49]:
total_ride_outside_KA = df[(df.pick_lat<=11.5945587) | (df.pick_lat>=18.4766494) | (df.pick_lng<=74.0543908) | (df.pick_lng>=78.5875761) | (df.drop_lat<=11.5945587) | (df.drop_lat>=18.4766494) | (df.drop_lng<=74.0543908) | (df.drop_lng>=78.5875761)]

In [50]:
print("Total Ride Outside Karnataka: {}".format(len(total_ride_outside_KA)))

Total Ride Outside Karnataka: 7048

### Total Ride Outside Karnataka: 7048
### OLA Bikes doesnot provide intercity requests. Considering these as system error requests

In [51]:
## Rides for which geodesic distance > 500kms
## Pickup and drop not of KA (state where we have maximum booking requests and user base)
suspected_bad_rides = total_ride_outside_KA[total_ride_outside_KA.geodesic_distance > 500]
suspected_bad_rides

,ts,number,pick_lat,pick_lng,drop_lat,drop_lng,mins,hour,day,month,year,dayofweek,booking_timestamp,shift_booking_ts,booking_time_diff_hr,booking_time_diff_min,geodesic_distance
6848,2020-12-31 18:24:14,1079,23.059650,72.592384,12.985226,77.567955,24,18,31,12,2020,3,1609439,1603531,1,98,1232.88
8515,2020-06-05 16:41:41,1378,12.910915,77.610085,19.766151,74.477840,41,16,5,6,2020,4,1591375,1586805,1,76,829.07
9553,2020-07-21 07:06:21,1566,12.893449,77.623940,21.195150,72.795494,6,7,21,7,2020,1,1595315,1594216,0,18,1052.50
12435,2020-04-27 22:00:45,2074,12.948681,77.648940,30.316494,78.032190,0,22,27,4,2020,0,1588024,0,441,26467,1923.56
15676,2020-06-05 20:27:56,2643,12.977254,77.549220,28.552588,77.246270,27,20,5,6,2020,4,1591388,0,442,26523,1724.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542361,2020-06-17 12:28:40,99158,12.963843,77.577484,26.842180,80.938576,28,12,17,6,2020,2,1592396,1591445,0,15,1575.95
543071,2020-07-11 12:47:54,99271,12.908705,77.586120,18.530767,73.848020,47,12,11,7,2020,5,1594471,1586799,2,127,739.86
543779,2020-06-24 16:34:35,99395,12.972305,77.614930,28.979435,77.689580,34,16,24,6,2020,2,1593016,0,442,26550,1772.36
543780,2020-07-29 15:29:45,99395,12.975827,77.605644,28.979435,77.689580,29,15,29,7,2020,2,1596036,1593084,0,49,1771.97
546285,2020-06-20 15:09:58,99817,12.973216,77.717860,27.299267,75.956764,9,15,20,6,2020,5,1592665,1589621,0,50,1596.61

### There are 170 rides which are >500kms geodesic distance and are pickup & drop outside KA, these are suspected rides.

In [52]:
df = df[~df.index.isin(suspected_bad_rides.index)].reset_index(drop = True)

In [53]:
print("Number of Good Ride Requests: {}".format(len(df)))

Number of Good Ride Requests: 547349

In [54]:
dataset = df[['ts', 'number', 'pick_lat','pick_lng','drop_lat','drop_lng','geodesic_distance','hour','mins','day','month','year','dayofweek','booking_timestamp','booking_time_diff_hr', 'booking_time_diff_min']]

In [55]:
dataset.to_csv('C:/Sachin/project/Bike-Taxi-Rides-Request-Demand-Forecast/data/clean_data.csv',index = False, compression = 'gzip')

## Statistic

### Ride request of same user with same timestamp: 113540
### None user_id: 116
### Number of requests to same pickup lat-long by a user within 1hour: 5,066,614
### Number of rides by a user within 8 mins of booking to different pickup lat-long: 26,97,418
### Number of Rides Requests less than 50meters of pickup and drop: 3,685
### Number of Rides pickup or drop lat-long outside India: 146

### Our majority ride state is from Karnataka (Bangalore)
### Total Ride Outside Karnataka (pickup or drop): 7,048
### Rides which are outside KA and pickup to drop distance is >500kms: 170

## Number of Good Ride Requests: 5,47,349